<?php
// INCLUI O ARQUIVO DE FUNCOES
require_once('../../includes/config.php');
require_once('../../includes/functions.php');

// CONECTA NO BANCO DE DADOS
$conn = connect();

// PEGA O ID DA TASK
$id = sanitize( $_REQUEST['id'] );

// PEGA OS DADOS DA TASK
$task = select(
	'tasks t',
	array( 't.idHistory','t.idStatus','t.idUser','t.text' ),
	array( 't.id = '.$id )
);

// TODO: Pegar dados da tabela de status
// MONTA O ARRAY DE STATUS
$status = array(
	1 => 'Todo',
	2 => 'Wip',
	3 => 'Done'
);

// PEGA OS USUARIOS
$users = select(
	'users u',
	array( 'u.id','u.name' )
);
?>
<form method="post" onsubmit="return Save.task();">
	<input type="hidden" name="action" value="edtTask" />
	<input type="hidden" name="id" value="<?= $_REQUEST['id']; ?>" />
	<div class="response"></div>

	<label for="idUser">Owner:</label>
	<?= mountSelect( $users['data'],'idUser',$task['data'][0]['idUser'] ); ?>

	<br /><br />

	<label for="status">Status:</label>
	<span><?= $status[ $task['data'][0]['idStatus'] ];?></span>

	<br /><br />

	<label for="text">Description:</label>
	<textarea name="text" rows="5"><?= stripslashes( $task['data'][0]['text'] ); ?></textarea>

	<br />

	<input type="submit" value="Save task" />
</form>